# Docker image build file.
# TAG: yukpiz/debian:rails

FROM debian
MAINTAINER yukpiz<yukpiz@gmail.com>

RUN cat /etc/debian_version
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y git
