# Docker image build file.
# TAG: yukpiz/ubuntu:base

FROM ubuntu:14.04
MAINTAINER yukpiz<yukpiz@gmail.com>

WORKDIR ~
RUN apt-get update
RUN apt-get upgrade
RUN apt-get install -y wget
RUN apt-get install -y gcc
RUN apt-get install -y make
RUN apt-get install -y git
RUN apt-get install -y mercurial
